import "./src/styles/global.css"

import "./src/styles/tailwind-typography/prose.css"
import "./src/styles/tailwind-typography/sizes/sm.css"
import "./src/styles/tailwind-typography/sizes/base.css"
import "./src/styles/tailwind-typography/sizes/lg.css"
import "./src/styles/tailwind-typography/sizes/xl.css"
import "./src/styles/tailwind-typography/sizes/2xl.css"
import "./src/styles/tailwind-typography/colors/gray.css"
import "./src/styles/tailwind-typography/colors/slate.css"
import "./src/styles/tailwind-typography/colors/zinc.css"
import "./src/styles/tailwind-typography/colors/neutral.css"
import "./src/styles/tailwind-typography/colors/stone.css"